version: '3.8'

services:
  mongodb:
    image: 'mongo'
    volumes:
      - ./data:/data/db
    env_file:
      - ./config/.production.env

  finra-api:
    build: ./
    ports:
      - '3001:3001'
    env_file:
      - ./config/.production.env
    depends_on:
      - mongodb

  analyzer:
    image: 'ghcr.io/samgozman/go-finra-short-sales-analyzer:latest'
    restart: unless-stopped
    ports:
      - '3030:3030'
    env_file:
      - ./config/.production.env
    depends_on:
      - mongodb
