FROM node:18-alpine3.17 AS build-env
WORKDIR /app
COPY package.json ./
RUN npm install
COPY . ./
EXPOSE 3001
RUN npm run build

FROM gcr.io/distroless/nodejs18-debian11
COPY --from=build-env /app /app
WORKDIR /app
ARG MONGODB_URL=mongodb
ARG MONGODB_NAME=finra-short-api
ARG MONGODB_PORT=27017
ARG MONGO_INITDB_ROOT_USERNAME=admin
ARG MONGO_INITDB_ROOT_PASSWORD=secret
ARG JWT_SECRET=SomeRandomString
ARG ADMIN_SECRET=RandomSecretForUserCreationRoute
ARG SENTRY_DSN=https://public@sentry.example.com/1
ARG SENTRY_TRACE_RATE=0.25
ARG ANALYZER_URL=http://analyzer:3030/run

ENV MONGODB_URL=${MONGODB_URL}
ENV MONGODB_NAME=${MONGODB_NAME}
ENV MONGODB_PORT=${MONGODB_PORT}
ENV MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
ENV MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
ENV JWT_SECRET=${JWT_SECRET}
ENV ADMIN_SECRET=${ADMIN_SECRET}
ENV SENTRY_DSN=${SENTRY_DSN}
ENV SENTRY_TRACE_RATE=${SENTRY_TRACE_RATE}
ENV PORT=3001
ENV ANALYZER_URL=${ANALYZER_URL}

CMD ["dist/main.js"]
