name: Publish to remote server

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish-finra-short-api-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build the finra-short-api Docker image
        run: |
          docker build . -t ghcr.io/samgozman/finra-short-api:latest
          docker push ghcr.io/samgozman/finra-short-api:latest
