name: Test finra-short-api

on:
  push:
    branches: [main, dev, finra-short-api-3.0]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18']
    name: Node ${{ matrix.node }} sample
    env:
      PORT: ${{ secrets.PORT }}
      MONGODB_CONNECTION_URL: ${{ secrets.MONGODB_CONNECTION_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      ADMIN_KEY: ${{ secrets.ADMIN_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run build
      - run: npm run docker:run:test:e2e
