name: Test finra-short-api

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18']
    name: Node ${{ matrix.node }} sample
    env:
      PORT: ${{ secrets.PORT }}
      MONGODB_CONNECTION_URL: ${{ secrets.MONGODB_CONNECTION_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      ADMIN_KEY: ${{ secrets.ADMIN_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run build
      - name: Create .env file
        run: |
          touch ./config/.development.env
          echo NODE_ENV=test >> ./config/.development.env
          echo PORT=3001 >> ./config/.development.env
          echo POSTGRES_HOST=postgres >> ./config/.development.env
          echo POSTGRES_PORT=5432 >> ./config/.development.env
          echo POSTGRES_USER=postgres >> ./config/.development.env
          echo POSTGRES_PASSWORD=postgres >> ./config/.development.env
          echo POSTGRES_DB=finra >> ./config/.development.env
          echo JWT_SECRET=someSecret >> ./config/.development.env
          echo ADMIN_SECRET=adminSecret >> ./config/.development.env
          echo SENTRY_DSN=https://public@sentry.example.com/1 >> ./config/.development.env
          echo SENTRY_TRACE_RATE=0 >> ./config/.development.env
      - run: npm run docker:run:test:e2e
